name = "VLChE5760Cornell"
uuid = "8f85c391-0665-4302-967b-eedfd53524ed"
authors = ["jdv27"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
